#############################################################################
# Makefile for building: ScanAndClip
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sat Jul 21 22:51:04 2012
# Project:  ScanAndClip.pro
# Template: app
# Command: /home/andrew/QtSDK/Desktop/Qt/474/gcc/bin/qmake -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++-64 -o Makefile ScanAndClip.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++-64 -I. -I../../QtSDK/Desktop/Qt/474/gcc/include/QtCore -I../../QtSDK/Desktop/Qt/474/gcc/include/QtGui -I../../QtSDK/Desktop/Qt/474/gcc/include/QtXml -I../../QtSDK/Desktop/Qt/474/gcc/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/home/andrew/QtSDK/Desktop/Qt/474/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/andrew/QtSDK/Desktop/Qt/474/gcc/lib -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/andrew/QtSDK/Desktop/Qt/474/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		field.cpp \
		properties.cpp \
		goods.cpp \
		clipimages.cpp \
		selectimages.cpp \
		../../QtSDK/testBaseRecognise/baserecognise.cpp \
		algorithm.cpp \
		vectorp.cpp \
		managerofalgorithms.cpp \
		perceptron.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		field.o \
		properties.o \
		goods.o \
		clipimages.o \
		selectimages.o \
		baserecognise.o \
		algorithm.o \
		vectorp.o \
		managerofalgorithms.o \
		perceptron.o \
		moc_mainwindow.o
DIST          = ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/release.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf \
		ScanAndClip.pro
QMAKE_TARGET  = ScanAndClip
DESTDIR       = 
TARGET        = ScanAndClip

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ScanAndClip.pro  ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++-64/qmake.conf ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/release.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++-64 -o Makefile ScanAndClip.pro
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/release.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++-64 -o Makefile ScanAndClip.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ScanAndClip1.0.0 || $(MKDIR) .tmp/ScanAndClip1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ScanAndClip1.0.0/ && $(COPY_FILE) --parents mainwindow.h field.h properties.h goods.h clipimages.h selectimages.h ../../QtSDK/testBaseRecognise/baserecognise.h algorithm.h vectorp.h managerofalgorithms.h perceptron.h .tmp/ScanAndClip1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp field.cpp properties.cpp goods.cpp clipimages.cpp selectimages.cpp ../../QtSDK/testBaseRecognise/baserecognise.cpp algorithm.cpp vectorp.cpp managerofalgorithms.cpp perceptron.cpp .tmp/ScanAndClip1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/ScanAndClip1.0.0/ && (cd `dirname .tmp/ScanAndClip1.0.0` && $(TAR) ScanAndClip1.0.0.tar ScanAndClip1.0.0 && $(COMPRESS) ScanAndClip1.0.0.tar) && $(MOVE) `dirname .tmp/ScanAndClip1.0.0`/ScanAndClip1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ScanAndClip1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ui_mainwindow.h \
		goods.h \
		clipimages.h \
		properties.h \
		field.h \
		/home/andrew/QtSDK/testBaseRecognise/baserecognise.h \
		managerofalgorithms.h \
		algorithm.h \
		vectorp.h \
		perceptron.h \
		selectimages.h \
		mainwindow.h
	/home/andrew/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/andrew/QtSDK/Desktop/Qt/474/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		ui_mainwindow.h \
		goods.h \
		clipimages.h \
		properties.h \
		field.h \
		/home/andrew/QtSDK/testBaseRecognise/baserecognise.h \
		managerofalgorithms.h \
		algorithm.h \
		vectorp.h \
		perceptron.h \
		selectimages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		goods.h \
		clipimages.h \
		properties.h \
		field.h \
		/home/andrew/QtSDK/testBaseRecognise/baserecognise.h \
		managerofalgorithms.h \
		algorithm.h \
		vectorp.h \
		perceptron.h \
		selectimages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

field.o: field.cpp field.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o field.o field.cpp

properties.o: properties.cpp properties.h \
		field.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o properties.o properties.cpp

goods.o: goods.cpp goods.h \
		properties.h \
		field.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o goods.o goods.cpp

clipimages.o: clipimages.cpp clipimages.h \
		properties.h \
		field.h \
		/home/andrew/QtSDK/testBaseRecognise/baserecognise.h \
		managerofalgorithms.h \
		algorithm.h \
		vectorp.h \
		perceptron.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clipimages.o clipimages.cpp

selectimages.o: selectimages.cpp selectimages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o selectimages.o selectimages.cpp

baserecognise.o: ../../QtSDK/testBaseRecognise/baserecognise.cpp ../../QtSDK/testBaseRecognise/baserecognise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o baserecognise.o ../../QtSDK/testBaseRecognise/baserecognise.cpp

algorithm.o: algorithm.cpp algorithm.h \
		vectorp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o algorithm.o algorithm.cpp

vectorp.o: vectorp.cpp vectorp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vectorp.o vectorp.cpp

managerofalgorithms.o: managerofalgorithms.cpp managerofalgorithms.h \
		algorithm.h \
		vectorp.h \
		perceptron.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o managerofalgorithms.o managerofalgorithms.cpp

perceptron.o: perceptron.cpp perceptron.h \
		vectorp.h \
		algorithm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o perceptron.o perceptron.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

